#!/bin/sh

if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]]
then
#  echo "BLA"
  exec startx -- -nocursor xterm
#  cd ~/xpcockpit/xppi/src
#  ./xppi boeing737fmc1 &
#  cd ~/xpcockpit/xpopengc/src/main
#  startx ./xpopengc boeing737fmc1 -- -nocursor
fi
